# Clojure CircleCI 2.0 configuration file
#
version: 2
jobs:

  lint:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.697-node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache: # restores saved cache if checksum hasn't changed since the last run
          key: clj-lint-dependencies-{{ checksum "deps.edn" }}

      - run: clojure -Mlint

      - save_cache: # generate and store cache in the .m2 directory using a key template
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: clj-lint-dependencies-{{ checksum "deps.edn" }}

  test-linux-jdk8:
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps-1.10.1.697-node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache: # restores saved cache if checksum hasn't changed since the last run
          key: clj-test-dependencies-{{ checksum "deps.edn" }}

      # run tests
      - run: scripts/ci-linux-test

      - save_cache: # generate and store cache in the .m2 directory using a key template
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: clj-test-dependencies-{{ checksum "deps.edn" }}

  test-linux-jdk11:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.697-node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache: # restores saved cache if checksum hasn't changed since the last run
          key: clj-test-dependencies-{{ checksum "deps.edn" }}

      # run tests
      - run: scripts/ci-linux-test

      - save_cache: # generate and store cache in the .m2 directory using a key template
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: clj-test-dependencies-{{ checksum "deps.edn" }}

  test-macos:
    macos:
      xcode: "12.4.0"

    working_directory: /Users/distiller/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - clj-test-dependencies-macos-{{ checksum "deps.edn" }}

      # - run: brew install clojure
      - run: sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
      - run: nix-env -i clojure
      - run: clojure -e "(clojure-version)"

      # run tests
      - run: scripts/ci-macos-test

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: clj-test-dependencies-macos-{{ checksum "deps.edn" }}

workflows:
  version: 2
  test:
    jobs:
      - lint
      - test-linux-jdk8
      - test-linux-jdk11
      - test-macos
