#!/usr/bin/env bash

set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

NATIVE_IMAGE=`which native-image` || true

if [ -z "$NATIVE_IMAGE" ]; then
  if [ -z "$GRAALVM_HOME" ]; then
      echo "Please set GRAALVM_HOME"
      exit 1
  fi

  NATIVE_IMAGE="$GRAALVM_HOME/bin/native-image"

  if [ ! -x "$NATIVE_IMAGE" ]; then
    "$GRAALVM_HOME/bin/gu" install native-image || true
  fi
fi

if [ -z "${1-}" ]; then
  jar="target/liz.jar"
  scripts/build-jar
else
  jar="$1"
fi

$NATIVE_IMAGE \
    -jar "$jar" \
    -H:Name=liz \
    -H:+ReportExceptionStackTraces \
    --initialize-at-build-time  \
    --verbose \
    --no-fallback \
    --no-server \
    "-J-Xmx3g" \
    --report-unsupported-elements-at-runtime \
    target/liz
