#!/usr/bin/env bash

set -xeuo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

curl "https://ziglang.org/download/${ZIG_VERSION}/zig-macos-x86_64-${ZIG_VERSION}.tar.xz" -O
tar xf "zig-macos-x86_64-${ZIG_VERSION}.tar.xz"
export PATH="zig-macos-x86_64-${ZIG_VERSION}:$PATH"

clojure -Mtest
